---
abstract: 'Perl extension to access redis database'
author:
  - 'Pavel Shaydo <zwon@cpan.org>'
build_requires:
  Digest::SHA: 0
  Test::Differences: 0.61
  Test::FailWarnings: 0
  Test::More: 0.96
  Test::Most: 0.22
  Test::TCP: 1.17
configure_requires:
  ExtUtils::MakeMaker: 6.3002
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.84, CPAN::Meta::Converter version 2.132830'
keywords:
  - redis
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: RedisDB
no_index:
  directory:
    - t
    - inc
requires:
  Encode: 2.1
  RedisDB::Parser: 2.2
  Try::Tiny: 0
  perl: 5.008004
resources:
  bugtracker: https://github.com/trinitum/RedisDB/issues
  homepage: https://github.com/trinitum/RedisDB
  license: http://dev.perl.org/licenses/
  repository: git://github.com/trinitum/RedisDB
version: 2.21_01
x_contributors:
  - 'Pavel Shaydo <zwon@cpan.org>'
  - 'HIROSE Masaaki <hirose31@gmail.com>'
  - 'Uwe Voelker <uwe.voelker@xing.com>'
  - "Andrew O'Brien"
