---
abstract: 'Perl extension to access redis database'
author:
  - 'Pavel Shaydo, C<< <zwon at cpan.org> >>'
  - 'Pavel Shaydo <zwon@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.62
  Test::Differences: 0.61
  Test::More: 0.96
  Test::Most: 0.22
  Test::use::ok: 0
configure_requires:
  ExtUtils::MakeMaker: 6.62
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.04'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: RedisDB
no_index:
  directory:
    - inc
    - t
requires:
  Try::Tiny: 0
  perl: 5.8.4
resources:
  bugtracker: http://github.com/trinitum/RedisDB/issues
  homepage: http://github.com/trinitum/RedisDB
  license: http://dev.perl.org/licenses/
  repository: git://github.com/trinitum/RedisDB
version: 0.27
